language: node_js

node_js:
  - "12.4.0"

sudo: true

env:
  - CXX=g++-4.8
  - NODE_ENV=testing
  - DB_USERNAME=wtraining
  - DB_NAME_DEV=db_wtraining_dev
  - DB_NAME_TEST=db_wtraining_test                  

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

install:
  - npm i

before_script:
  - psql -c "CREATE DATABASE $DB_NAME_TEST;" -U postgres

script: 
  - npm run lint
  - npm run test

# after_script:
#  - notificar en un canal de slack con un webhook
